version: '3'
volumes:
  mssql_data:
      driver: local
  mysql_data:
      driver: local

services:
  mssql:
      container_name: mssql
      image: mcr.microsoft.com/mssql/server:2019-latest
      ports:
        - "14330:1433"
      environment:
        - ACCEPT_EULA=Y
        - MSSQL_PID=Developer
        - SA_PASSWORD=Password!23
      volumes:
        - mssql_data:/var/lib/mssql
  mysql:
      container_name: mysql
      image: mysql:5.7
      volumes:
        - mysql_data:/var/lib/mysql
      ports:
        - "33060:3306"
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: keycloak
        MYSQL_USER: keycloak
        MYSQL_PASSWORD: password
  keycloak:
      container_name: keycloak
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: mysql
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_PASSWORD: password
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the MySQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "connectTimeout=30000"
      ports:
        - 8080:8080
      depends_on:
        - mysql